### ISSUE TITLE
Project not loading correctly in Unity

### ISSUE THREAD

**Issue by thesoulharmonic** [ahmaderfani12/PointClouds#2]
Hi, really love the work you've done with PointClouds and the mesh rendering but I'm having trouble opening the Unity demos (I'm using the same Unity version 2019.4.9f1)

These are the errors I'm getting. 
Assets/Project/Effects/Mesh Distortion/DistortionMeshInputControl.cs(9,37): warning CS0649: Field 'DistortionMeshInputControl.DistortionMesh' is never assigned to, and will always have its default value null

Assets/Project/Effects/TouchableMesh/TouchableMesh.cs(8,41): warning CS0649: Field 'TouchableMesh.handSphere' is never assigned to, and will always have its default value null

Assets/Project/Effects/AntiAbsoringMesh/AntiAbsoringMesh.cs(7,41): warning CS0649: Field 'AntiAbsoringMesh.handSphere' is never assigned to, and will always have its default value null

Do you know what it could be?

Thank you

**Comment by thesoulharmonic** [comment]
<img width="832" alt="Screenshot 2022-02-21 at 15 29 18" src="https://user-images.githubusercontent.com/22345281/154985039-3e1a32cf-e63c-4073-96de-596a73245fe8.png">

This is all I see

**Comment by ahmaderfani12** [comment]
Hi, and thanks :)
Well the good news is that you can use it in a newer version and it's OK( I have tested it on 2021.1.21f1)
For your case, it seems component properties are lost and you have to set them manually.
For instance, the 'SingelMeshView' scene 'MeshGen' component should be like this:
![image](https://user-images.githubusercontent.com/48528993/154993867-3b6bc3c3-ab8b-4a2b-8aa6-af0ec60e3fe7.png)

**Comment by thesoulharmonic** [comment]
Yeah that's what the settings are set at. Also tried it in a newer version of Unity and no luck!

**Comment by ahmaderfani12** [comment]
Oops, it's weird!
I will check it. meantime you may find a solution in:
https://answers.unity.com/questions/1616705/serializefield-field-is-never-assigned-to-and-will.html
https://answers.unity.com/questions/60461/warning-cs0649-field-is-never-assigned-to-and-will.html

**Comment by thesoulharmonic** [comment]
Thanks I'll have a look
