### ISSUE TITLE
Point cloud disappears if origin outside camera frustum (AntiAbsoring)

### ISSUE THREAD

**Issue by albrrt** [ahmaderfani12/PointClouds#3]
Hi thanks for sharing your point cloud project, this is awesome.

I noticed the point cloud disappears if I move the camera very close or inside the point cloud - essentially when the origin of the point cloud is not in the camera frustum. 

People who ran into [similar issues](https://answers.unity.com/questions/1710703/how-to-prevent-frustum-culling-when-using-a-vertex.html) recommended setting the mesh bounds to a higher value but you seem to do this already on line 126:

`  private void SetBound()
    {
        bounds = new Bounds(Vector3.zero, Vector3.one * 200);
    }`

Do you know what else could be causing this issue?

I noticed this happens in the AntiAbsoring and Touchable scene but not in the single MeshView scene. 

Thanks!

**Comment by ahmaderfani12** [comment]
Hi Albrrt, glad you liked it.

A line of code was missing in those scenes.
Now it's resolved.
